name = "qaelevate-frontend"
compatibility_date = "2024-11-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2024-11-16"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2024-11-16"
compatibility_flags = ["nodejs_compat"]
